apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: order
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 5
  replicas: 2
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
